### ISSUE TITLE
Is there any example code, you can share it here

### ISSUE THREAD

**Issue by SubraGomz** [dlenroc/node-testrail-api#41]

**Comment by dlenroc** [comment]
It is not clear what you mean and what problem you are facing, but examples are shown in `README.md` and `tests`, but you can also see how others use this dependency [here](https://github.com/dlenroc/node-testrail-api/network/dependents?package_id=UGFja2FnZS0xNDkxNzQ4MzE2)

PS: If you have questions related to TestRail itself but not to this binding then it is better to ask them in the TestRail support / forum:

- https://discuss.gurock.com/ - forum where all king of questions related to TestRail can be asked
- https://www.gurock.com/testrail/docs/api/getting-started/introduction - how to enable API & documentation
