### ISSUE TITLE
Use of Proxy with TestRail API

### ISSUE THREAD

**Issue by bgeaney** [dlenroc/node-testrail-api#49]
When we push our results from our automated tests to Testrail behind our corporate firewall they fail but when pushed outside the corporate firewall they work with no issues.
Is there a way to use a proxy with the TestRail API.

**Comment by dlenroc** [comment]
Have you tried [global-agent](https://github.com/gajus/global-agent) ?

A simple example with one of several methods supported by global-agent

```js
import 'global-agent/bootstrap.js';

import TestRail from '@dlenroc/testrail';

;(async () => {

  const api = new TestRail({
    host: 'https://{organization}.testrail.net',
    username: '{username}',
    password: '{token/password}',
  });
  
  const projects = await api.getProjects();
  console.log(projects);

})();
```

```shell
export GLOBAL_AGENT_HTTP_PROXY=http://127.0.0.1:8888

node proxy-example.mjs
```

**Comment by dlenroc** [comment]
I'll close this question because `global-agent` allows you to set up a proxy.

**Comment by bgeaney** [comment]
Hi @dlenroc 
Thanks for the info. I've looked into it and It looks I also need a cert as part of accessing on my site using global-agent. global-agent does not currently have that functionality but there seems to be a pull request for it created by someone. I'll contact that person going forward. Once again thanks for response and info.

**Comment by dlenroc** [comment]
@bgeaney I'm not sure about your certificate/setup/error, but have you tried installing your cert into your system and make it trusted ?

I tested `global-agent` with `Charles Proxy` which also uses `ssl` certificate to intercept https traffic and everything worked well.

> In case installing & trusting certificate will not help you should be able to get help from `global-agent` as you mentioned or finding a different solution for node.js ecosystem which has that ability
