### ISSUE TITLE
getCases require  suite_ID which is  missing   as parameter in methode

### ISSUE THREAD

**Issue by mykhailo-kobylianskyi** [dlenroc/node-testrail-api#55]
<img width="593" alt="image" src="https://user-images.githubusercontent.com/16340722/175571886-bf58771a-a7a0-44e7-b1df-0b7153bfd775.png">
<img width="699" alt="image" src="https://user-images.githubusercontent.com/16340722/175571962-07841bb7-347d-446f-a75d-3cab72679a39.png">

**Comment by MKobylianskyi** [comment]
When project has multiple  test suites getCases api request require suite id, hence  doesn't work for those kind of projects

**Comment by mykhailo-kobylianskyi** [comment]
ow, i've found a solution [ in here ](https://github.com/dlenroc/node-testrail-api/issues/46#issuecomment-1092896338)
issue should be closed
