### ISSUE TITLE
How to update custom field with custom data?

### ISSUE THREAD

**Issue by NazarYermolenko** [dlenroc/node-testrail-api#61]
I manually created a test field in TestRail named additional_link (text area) , and while posting test results to Test Rail, I need to fill the field with some data, I didn't find the method in TestRail official documentation, and decided to ask you. Please provide some advices... 
I tried to add the data while creating of test case but it doesn't appear in TestRail

**Comment by dlenroc** [comment]
From official documentation:

> https://support.gurock.com/hc/en-us/articles/7077819312404-Results#addresult
> Custom fields are supported as well and must be submitted with their system name, prefixed with custom_, e.g.: "custom_comment": "This is a custom comment"


Example with that library:

```typescript
await api.addResultsForCases(1 /* run id */, {
  results: [
    {
       status_id: 5, /* status id */
       case_id: 1, // * case id */
       custom_additional_link: "https://support.gurock.com/hc/en-us/articles/7077819312404-Results#addresult",
       custom_comment: "This is a custom comment"
    },
    ... // more results
  ]
})
```


PS: TestRail server/cloud uses this approach in all of its endpoints.
