### ISSUE TITLE
Per-request timeout

### ISSUE THREAD

**Issue by treyturner** [dlenroc/node-testrail-api#70]
Hi,
Occasionally TestRail API performance tanks and requests to open a test run via this library are hanging. I was interested in setting a request timeout, but it seems like the AbortController signal I pass when creating the TestRail client is reused, so the timeout I set there isn't per-request but for the runtime of my entire script.

Could you please explain if there's a means by which I can set a request timeout per request?

```ts
function createAbortController(ms: number): AbortController {
  const ac = new AbortController();
  setTimeout(() => ac.abort(), ms);
  return ac;
}

const tr = new TestRail({
  // host, username, password...
  signal: createAbortController(10_000).signal,
});
```

**Comment by dlenroc** [comment]
There is currently no way to set a per-endpoint timeout unless separate instances/signals are used.

```typescript
const config = {
  // host, username, password...
}

// can be extracted into a helper
const projects = await new TestRail({ ...config, signal: AbortSignal.timeout(10000) }).getProjects()
```

-----

I thought about a timeout for each method but haven't added them yet

```typescript
await api.getProjects();                       // without optional parameters
await api.getProjects({ is_completed: false }); // with optional parameters

// don't like mixing payload with config
await api.getProjects({ is_completed: false, signal: ... });

// good, but too verbose
await api.getProjects({}, { signal: ... });
await api.getProjects({ is_completed: false }, { signal: ... });
```

I can implement the last option since no better idea comes to mind.

**Comment by treyturner** [comment]
That would be cool! Thanks for your consideration and the workaround.

**Comment by dlenroc** [comment]
I added the ability to set `AbortSignal` for each method in version `1.9.0`.

----

```typescript
const abortController = new AbortController();

const api = new TestRail({
  host: '...',
  username: '...',
  password: '...',

  // aborts all pending instance requests and prevents future
  signal: abortController.signal,
});

// will be aborted when the first signal is interrupted (either `instance` or `method` signal)
const projects = await api.getProjects(
  {
    is_completed: false
  },
  {
    // aborts specific method
    signal: AbortSignal.timeout(10000),
  }
);

// abort all requests made with the current `api` instance
abortController.abort();
```

It is also now possible to provide a custom implementation of `AbortController`, `Blob`, `fetch` and `FormData`.

```typescript
const api = new TestRail({
  /* standard parameters (haven't changed) */,

  // overrides the API implementation to be used (make possible to use ponyfills)
  implementations: { AbortController, Blob, fetch, FormData }
});
```

**Comment by treyturner** [comment]
Apologies, but I can't seem to figure out how to make this work using TypeScript and Node 16 which doesn't have `AbortSignal.timeout()`. Maybe you can spot what I'm doing wrong.

My code was only slightly modified from before; I have a method that creates an `AbortController` on which `.abort()` will be called in `ms` ms, and which returns its `signal` (an `AbortSignal`):
```
export const abortAfter = (ms: number): AbortSignal => {
  const ac = new AbortController();
  setTimeout(() => ac.abort(), ms);
  return ac.signal;
};
```
I then tried to use the signal how I believe you suggsted:

```
await tr.api.addRun(projectId, payload, { signal: abortAfter(60_000) });
```

TypeScript seems to approve of all this. When I use it however, the call goes through, but then my script hangs for 60s before it ends. Any ideas? I suspect I could call the signal myself after the call but it seems like that shouldn't be needed.

Thanks so much for your time.

**Comment by dlenroc** [comment]
everything worked as expected, you used 60_000 ms which is equivalent to 60s.
 > ie: if you use 1000 ms then the method will get interrupted after 1s and so on.
 
 You can review https://developer.mozilla.org/en-US/docs/Web/API/AbortController to better understand how it works and what can be done.

**Comment by treyturner** [comment]
Thanks! It turns out it wasn't related to the AbortController or Signal but that my `setTimeout` needed to be cleared with `clearTimeout()`. This worked for me, maybe it will help someone else some day.

```
export const createAbortController = (ms: number): { signal: AbortSignal; timeout: NodeJS.Timeout } => {
  const ac = new AbortController();
  const timeout = setTimeout(() => ac.abort(), ms);
  return { signal: ac.signal, timeout };
};

const { signal, timeout } = createAbortController(60_000);
const run = await tr.api.addRun(projectId, payload, { signal });
clearTimeout(timeout);
```
